# This is a basic workflow to help you get started with Actions
# 
name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Read template from file
      id: template
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: https://dgithub.xyz/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

    - name: Get the template output
      run: echo "${{ steps.template.outputs.content }}"



- name: Run Workflow
  id: write_file
  uses: timheuer/base64-to-file@v1.2
  with:
    fileName: 'freenode-base64-2'
    fileDir: './main/'
    encodedString: ${{ secrets.SOME_ENCODED_STRING }}
