# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: collect-convert

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Workflow
      id: write_file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'freenode-base64-2'
        fileDir: './main/'
        encodedString: ${{ steps.template.outputs.content }}
